### ISSUE TITLE
Why run introspect on module load? It fails without mplayer in path

### ISSUE THREAD

**Issue by olegantonyan** [baudm/mplayer.py#22]
If I don't have `mplayer` in PATH and specify it with `mplayer.Player.exec_path = /whatever/mplayer` then I get errors:

```
AttributeError: 'Player' object has no attribute 'loadfile'
```

I found that this is because all those dynamic methods/are generated by `introspect` class method. It runs on module import, but there is no `mplayer` in PATH already, then it fails silently

``` python
# Introspect on module load
try:
    Player.introspect()
except OSError:
    pass
```

Then I specify exec path and get errors for every dynamic attribute because then has not been generated.
I've added `mplayer.Player().introspect()` after specifying `exec_path` and it works, but it's just a workaround. 

I'm wondering why `introspect()` gets called on module import and not in `__init__`, for example? Also, why specify `exec_path` on class level and not pass it as a parameter? Should I submit PR to fix this or there is a good reason why it's done this way?

**Comment by baudm** [comment]
`introspect()` getting called on module load is just for convenience. In most cases (especially on Linux), MPlayer is already available in the path and `introspect()` is ready to be called. It's done on the class level to avoid the overhead of running MPlayer, parsing it's output, and generating properties and methods on-the-fly each time an instance is created. Since in most use cases, there's only one MPlayer binary being used by the wrapper, it makes more sense to do the introspection once rather done repeating it every `__init__`.

I hope this gives more insight on why I implemented it that way. If you think you have a better design, feel free to open a pull request.

**Comment by baudm** [comment]
Closing this issue now since this behavior is actually documented in the wiki.
