### ISSUE TITLE
Error when running py 32bit on a 64bit system

### ISSUE THREAD

**Issue by FallenSpaces** [baudm/mplayer.py#34]
I'm trying to do this

`import mplayer`
`url = "https://www.youtube.com/watch?v=n93bga1b1gs&t=7s"`
`print url`
`p = mplayer.Player()`

But I'm getting this:

`Traceback (most recent call last):`
`  File "\test.py", line 36, in <module>`
`    stream = Stream()`
`  File "\test.py", line 19, in __init__`
`    p = mplayer.Player()`
`  File "\mplayer\core.py", line 110, in __init__`
`    self.spawn()`
`  File "C:\Python27\lib\site-packages\mplayer\core.py", line 324, in spawn`
`    close_fds=(sys.platform != 'win32'))`
`  File "C:\Python27\lib\subprocess.py", line 390, in __init__`
`    errread, errwrite)`
`  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child`
`    startupinfo)`
`WindowsError: [Error 2] The system cannot find the file specified`

**Comment by brettroyer** [comment]
I was getting this error as well.  It may be due to the location of your mplayer.exe.  Mine was in a sub-directory called player so before instantiating the class,   you may have to define the exec_path as I did.  See PIC below.

Now on to figure out how to stream a internet radio URL using this!!

![image](https://user-images.githubusercontent.com/13924122/49704201-a3d43780-fbd5-11e8-9c02-824cfac153f9.png)

**Comment by FallenSpaces** [comment]
So that worked for you? If so it would be amazing, because this stopped my whole project dead in its tracks.

**Comment by baudm** [comment]
As commented by @brettroyer, you need to specify the full path to the executable. Closing this now.
